### ISSUE TITLE
Trouble getting this working in a wordpress network 

### ISSUE THREAD

**Issue by mpaskevi** [clintlalonde/oEmbed-BCcampus#1]
Hi Clint, having trouble getting this working in our WP networks. I have customized the plugin with our base strings, used the oembed url in a WP post, and no dice. Was there anything else you had to tweak in the kaltura app?  Thanks in advance.

**Comment by clintlalonde** [comment]
In the KMS (Mediaspace) admin area you also have to enable the oEmbed module.  Add the code of the player you want to use (you can get this code from the player in the KMC Studio). 
![image](https://user-images.githubusercontent.com/679506/26842658-752c9aca-4aa2-11e7-9e24-74b16602e85a.png)

**Comment by mpaskevi** [comment]
The module is enabled. I am using oembed links in wp with no success.
